<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets/app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Copyright>Copyright © FreeGen</Copyright>
    <Company>FreeGen</Company>
    <Description>EZ2Play Game Launcher</Description>
    <Product>EZ2Play Game Launcher</Product>
    <AppName>EZ2Play</AppName>
    <AppDescription>EZ2Play Game Launcher</AppDescription>
    <Version>1.3.15</Version>
    <AssemblyVersion>1.3.15</AssemblyVersion>
    <FileVersion>1.3.15</FileVersion>
    <InformationalVersion>1.3.15</InformationalVersion>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugSymbols>false</DebugSymbols>
    <DebugType>none</DebugType>
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>false</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Fody" Version="6.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <PackageReference Include="Costura.Fody" Version="5.7.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>

    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.26100.4948" />
    <PackageReference Include="SharpDX.XInput" Version="4.2.0" />
    <PackageReference Include="WPF-UI" Version="4.2.0" />

    <Reference Include="System.Drawing" />
    <Reference Include="System.Net.Http" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Management" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
    
  <ItemGroup>
    <EmbeddedResource Include="Assets/Focus.mp3" />
    <EmbeddedResource Include="Assets/Invoke.mp3" />
    <EmbeddedResource Include="Assets/Back.mp3" />
    <EmbeddedResource Include="Assets/Event.mp3" />
    <EmbeddedResource Include="Assets/Tab.mp3" />
    <EmbeddedResource Include="Assets/Ambient.mp3" />

    <Resource Include="Assets/Manrope-VariableFont_wght.ttf" />
    <Resource Include="Assets/XboxFluent.ttf" />
    <Resource Include="Assets/Logo.png" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyMetadata Include="AppName" Value="$(AppName)" />
    <AssemblyMetadata Include="AppDescription" Value="$(AppDescription)" />
    <AssemblyMetadata Include="Company" Value="$(Company)" />
    <AssemblyMetadata Include="FileVersion" Value="$(FileVersion)" />
  </ItemGroup>

  <Target Name="RemoveAppConfigInRelease" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <Delete Files="$(TargetPath).config" ContinueOnError="true" />
  </Target>
</Project>